HelpInfo,C:\Microsemi\Libero_v11.5\Synopsys\synplify_I201403MSP1\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_v11.5\Synopsys\synplify_I201403MSP1\bin\mbin\assistant
Implementation;Synthesis;RootName:ants_master
Implementation;Synthesis||(null)||Info: Interrupted by user!||(null);(null)||(null);(null)
Implementation;Compile;RootName:ants_master
Implementation;Compile||(null)||Please refer to the log file for details about 277 Warning(s) , 1 Info(s)||ants_master_compile_log.rpt;liberoaction://open_report/file/ants_master_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:ants_master
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||ants_master_placeroute_log.rpt;liberoaction://open_report/file/ants_master_placeroute_log.rpt||(null);(null)
Implementation;Generate BitStream;RootName:ants_master
Implementation;Generate BitStream||(null)||Please refer to the log file for details about 1 Info(s)||ants_master_prgdata_log.rpt;liberoaction://open_report/file/ants_master_prgdata_log.rpt||(null);(null)
